### ISSUE TITLE
[ Plots ] Brief for new visualization interface

### ISSUE THREAD

**Issue by NicolasGensollen** [aramis-lab/leaspy#51]
In GitLab by @Symcies on Oct 22, 2021, 16:12

### Context

Leaspy (& Leaspype) includes tools to plot various figures, from Leaspy progression models (unique or resampled) to statistical analysis of individual parameters.

### Current behavior

The plotters lack homogeneity across the code. There is no clear design as to :
1. what are the different plots i.e. the groups of plots related to different functionalities
2. how plots should be handled in the code,
3. how they should be used from a user perspective.

### Scope of the issue

I think that this issue should be about:
- Discussing our different usages & needs in term of Leaspy-related plots
- Structure these needs in term of families of plots. E.g. : plotter during the model iterations, Leaspy progression, statistical analysis of the individual parameters, statistical analysis of the reconstruction error
- Distinguish what is Leaspy versus Leaspype related

Once handled - and only then - we could discuss (here or other issue)
- Define a structure for these plots in term of code (API? other repo? distinction between Leaspy & Leaspype? etc) and related guidelines for future developments
- Coding it

Note: Quentin will soon join the Leaspy team. He is a dev/engineer that will work on Leaspy(pe) related issues. I believe that developing these visualisations/interfaces is a nice onboarding into Leaspy as it will help understand the Leaspy functionalities with visual outputs. 

### Expected plots (proposition for discussion)

I here try to distinguish different sets of plots

#### Plots 1: Convergence of the model

Plots related to the convergence of the model during the algorithm fit or personalization if applicable. In particular:
- Values of the features every N iterations
- Posterior distribution of a parameter (evaluated on the N last iterations, if sufficient - Note that it won't exactly be the posterior)

#### Plots 2: Progression of the biomarkers

We often display the progression of the variables of one or multiple leaspy models along time. It should also be backed up by a representation of the reparametrized ages of the participants to see the interpolation versus extrapolation, i.e. which part of the model were used to calibrate the model.

These plots should be displayed in their native or [0, 1] space.

Abnormalities are important to draw on top of the variable progression, along with the age at which they occur. 

A related plot is the boxplot of the ages at abnormalities. 

#### Plots 3: Individual progression

We often look at individual progressions and their fit to the input data - both interpolation/reconstruction, and also future predictions.

There exist multiple options :   
- one or multiple patients
- one or multiple features
- real age or reparametrized ages

#### Plots 4: Individual parameters

KDE plots of the individual parameters, esp. colored by cofactor types

#### Other plots

A task would be to go over all our publications (and potentially of collaborators) and list the one that we should add to our future visualization toolbox.

The issue is directly related to #45 and #19 

### Tasks (& respective owners) :

- [ ] @PEPoulet @little_nemo @JulietteOrtholand @cecdf2 @emaheux @Mkr\_ : Comment the proposition and suggest additional plots
- [ ] Quentin : Gather all propositions and organize them into a presentation. It will serve the purpose to structure a further discussion with all Leaspy user (Thursday meeting?)
- [ ] Igor : List all constraints in term of current & future needs (e.g. Leaspy vs Leaspype)
- [ ] Quentin: Convert defined needs into specs & related development

Note : Do not hesitate to paste your existing Figures to drive the discussion on concrete examples

### Milestone

Quentin, the new engineer, is about to join the team in November the 1st.
We should describe our needs beforehand to structure the development

**Comment by NicolasGensollen** [comment]
In GitLab by @Symcies on Oct 22, 2021, 16:12

changed due date to October 29, 2021

**Comment by NicolasGensollen** [comment]
In GitLab by @Symcies on Oct 22, 2021, 16:17

### Convergence of the model

There currently exists two files outputed during the convergence of the model calibration. They should be merged into one file only. Moreover, depending on the models, some plots are useless because there is no change by design 

![Capture_d_écran_2021-10-22_à_16.15.54](https://my-gitlab-bucket.s3.amazonaws.com/938594763/2922591354dbf90c936d05e98d6175a5a090d23407c51d0ee8ccbd67f7113e36/Capture_d_écran_2021-10-22_à_16.15.54.png)

![Capture_d_écran_2021-10-22_à_16.16.16](https://my-gitlab-bucket.s3.amazonaws.com/938594763/f1320d00e5b42b4431be61e3188359b7647eea83e24f26587e35f43c21982278/Capture_d_écran_2021-10-22_à_16.16.16.png)
 

- [ ] Igor : List all variables to display by model

**Comment by NicolasGensollen** [comment]
In GitLab by @Symcies on Oct 22, 2021, 16:24

### Progression of the biomarkers

Few initial propositions to discuss upon

##### Progression 

![Capture_d_écran_2021-10-22_à_16.23.24](https://my-gitlab-bucket.s3.amazonaws.com/938594763/5904c753a90c0abcc26f4d2573ddab87dd70a5ad3792e96d2e2bbf8c22d0e731/Capture_d_écran_2021-10-22_à_16.23.24.png)

##### Boxplot of the age at abnormalities

![Figure4](https://my-gitlab-bucket.s3.amazonaws.com/938594763/25da227f73be9e208b4a93834e01373e17bf0df7ef837b2915db747adf9f50aa/Figure4.png)

**Comment by NicolasGensollen** [comment]
In GitLab by @Symcies on Oct 22, 2021, 16:25

### Individual progressions

![Capture_d_écran_2021-10-22_à_16.25.38](https://my-gitlab-bucket.s3.amazonaws.com/938594763/84be705374ad32e5ad291ca4c5b95ff46005de42e0f0bf30fcda06aa1c34f851/Capture_d_écran_2021-10-22_à_16.25.38.png)

**Comment by NicolasGensollen** [comment]
In GitLab by @little_nemo on Oct 25, 2021, 10:08

There are also some “patients” plots generated during calibration, which are drawn every x iterations in a `plot_patients_{iteration}.pdf` file. I don't really know if anyone uses them, and what to look for in those plots. I tend to think that they are kind of unreadable, so I am not sure we want to keep them, unless there is a precise utility which I am missing...

![Capture_d_écran_2021-10-25_à_10.03.37](https://my-gitlab-bucket.s3.amazonaws.com/938594763/c6a75013c45a3382e30ce5f08d89764b6f4f346ea6acc2e37e8ab8a3a9459a14/Capture_d_écran_2021-10-25_à_10.03.37.png)

![Capture_d_écran_2021-10-25_à_10.07.22](https://my-gitlab-bucket.s3.amazonaws.com/938594763/0b5af44b7a1036fee4f8bb005a9cf12a8cbda0847261a389520f7bb0b5f2f876/Capture_d_écran_2021-10-25_à_10.07.22.png)

**Comment by NicolasGensollen** [comment]
In GitLab by @little_nemo on Oct 25, 2021, 10:35

I also think that it could be nice to highlight the difference between the burn-in and non burn-in phases on those convergence plots, because the convergence regimes tend to exhibit different behavior and a graphical indication that a shift in regime is indeed due to the switch between the memory-less and the exploitation phase could make the interpretation of the different regimes of convergence easier. 

Something like a simple vertical line between the two phases could be sufficient without making those graph harder to read I think.

**Comment by NicolasGensollen** [comment]
In GitLab by @little_nemo on Oct 25, 2021, 10:56

I like those plots, and I think they are worth being formalized into dedicated plotting methods (I think that the first plot can already be obtained fairly easily from Leaspype). 
Yet, from what I remember the computation of those abnormalities is not “straightforward”, as it includes logistic regressions to learn thresholds separating groups of reference (if I'm not mistaken). I think it might make this fall into the “harder statistical analysis” side that we wanted to hide from Leaspy in order to prevent inadequate statistical claims about the models without really understanding what is at stake. I don't know where we stand about this.

**Comment by NicolasGensollen** [comment]
In GitLab by @little_nemo on Oct 25, 2021, 11:13

I had some plots of this kind, especially for categorical (binary) data, on which a Leaspy model was calibrated with a cross-entropy loss. It is hard to represent this kind of data using a single plot when multiple features were involved. So here is a variation of what you show but for multiple features.

![image](https://my-gitlab-bucket.s3.amazonaws.com/938594763/ea52fe4df77a81a1e32cd84c4bc82630348f6b6ecaec0290c034618a6010a992/image.png)

**Comment by NicolasGensollen** [comment]
In GitLab by @cecdf2 on Oct 26, 2021, 10:08

One issue with this plot is that it quickly becomes hard to read as we add cohorts, and if i remember well I had some issues with the color legend when i tried to plot it with more than 5 cohorts

**Comment by NicolasGensollen** [comment]
In GitLab by @little_nemo on Nov 9, 2021, 14:26

marked the checklist item **Igor : List all constraints in term of current & future needs (e.g. Leaspy vs Leaspype)** as incomplete

**Comment by NicolasGensollen** [comment]
In GitLab by @emaheux on May 18, 2022, 18:30

removed due date
